import type { Metadata } from "next";
import { Source_Serif_4 } from "next/font/google";
import "@/app/globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
import { AuthProvider } from "@/context/AuthContext";
import { Toaster } from "@/components/ui/sonner";
import NextTopLoader from "nextjs-toploader";

const sourceSerif = Source_Serif_4({
  variable: "--font-source-serif",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${sourceSerif.variable} antialiased max-w-[1660px] w-full mx-auto `}
      >
        <NextTopLoader color="#C85990" height={3} showSpinner={false} />

        <AuthProvider>
          <Navbar />
          {children}
          <Toaster />
          <Footer />
          <Toaster richColors />
        </AuthProvider>
      </body>
    </html>
  );
}
